version: '3'
services:
  postgres:
    image: postgres:14.8
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: film_recommendation
    ports:
      - "127.0.0.1:5432:5432/tcp"
    expose:
      - "5432/tcp"
    restart: on-failure
#    volumes:
#      - ./dev/postgresql/:/var/lib/postgresql/data

  python:
#    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      TELEGRAM_TOKEN: <token>
    env_file:
      - .env
#      PYTHONPATH: "app/python"
#    volumes:
#      - ./ :/app/python
    depends_on:
      - postgres
    restart: on-failure
    command: python /app/python/src/chat/bot.py

  go-app:
    image: golang:latest
    container_name: parser
    volumes:
      - ./parser:/app/parser
    depends_on:
      - postgres
    expose:
      - "8080"
    restart: on-failure
    command: sh -c "cd /app/parser && go install && go run main.go"

volumes:
  postgres-data: